name: 4. Create D1 Schema
run-name: Create D1 Schema

on:
  workflow_dispatch:
    inputs:

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_D1_ID: ${{ secrets.CLOUDFLARE_D1_ID }}
  CLOUDFLARE_WORKER_NAME: ${{ vars.CLOUDFLARE_WORKER_NAME }}
  CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}

jobs:
  deploy_cloudflare_worker:
    runs-on: ubuntu-latest
    name: Create schema and table
    steps:
      - uses: actions/checkout@v4
      - name: Create D1 Schema
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          command: |
            d1 create contrails-auth
      - name: Create auth table
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          command: |
            d1 execute contrails-auth  --file=./cloudflare-worker/schema.sql